GET http://localhost:3000/sales/

###
POST http://localhost:3000/sales/file
Content-Type: : application/json

{
    "data":"name"
}

###
DELETE  http://localhost:3000/sales/

###
GET http://localhost:3000/upload-history/

###
POST http://localhost:3000/upload-history/
Content-Type: : application/json

{
    "data":"name"
}


###
DELETE  http://localhost:3000/upload-history/
