###
GET http://localhost:4000/sales/

###
POST http://localhost:4000/sales/file
Content-Type: : application/json

{
    "data":"name"
}

###
DELETE  http://localhost:4000/sales/

###
GET http://localhost:4000/upload-history/

###
POST http://localhost:4000/upload-history/
Content-Type: : application/json

{
    "file_name":"f1",
    "processed_rows": 8,
    "upload_date":"14/04/2025"
}


###
DELETE  http://localhost:4000/upload-history/
